version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  VCPKG_ROOT: C:\Tools\vcpkg
install:
- cmd: >-

    IF NOT EXIST "C:\Tools\vcpkg\installed\x64-windows\lib\boost_thread-vc140-mt.lib" vcpkg install gtest:x64-windows boost-thread:x64-windows boost-program-options:x64-windows liblemon:x64-windows
    
    curl https://gitee.com/freewind201301/appveyor-patch-liblemon/raw/master/preflow.h -o preflow.h
    
    copy preflow.h /Y C:\Tools\vcpkg\installed\x64-windows\include\lemon\
    
cache: C:\Tools\vcpkg\installed\x64-windows
before_build:
- cmd: >-
    git submodule update --init --recursive

    mkdir build

    cd build

    cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DENABLE_TESTING=ON ..\
build:
  project: build\ALL_BUILD.vcxproj
  verbosity: minimal
test_script:
- cmd: >-
    .\test\Release\TestAll.exe

    .\set\Release\test_set.exe

    .\Release\main.exe --help
