set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
if(PORT MATCHES "python3")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
set(VCPKG_PLATFORM_TOOLSET v141)
if(NOT DEFINED ENV{VS150COMNTOOLS})
    set(ENV{VS150COMNTOOLS} "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\")
endif()